# SearXNG Settings for MyDigitalAssistant
# https://docs.searxng.org/admin/settings/

use_default_settings: true

server:
  image_proxy: true

search:
  formats:
    - html
    - json

logger:
  log_level: WARNING
